package io.cequence.openaiscala.examples.anthropic.tools

import io.cequence.openaiscala.anthropic.domain.Message
import io.cequence.openaiscala.anthropic.domain.Message.{SystemMessage, UserMessage}
import io.cequence.openaiscala.anthropic.domain.settings.AnthropicCreateMessageSettings
import io.cequence.openaiscala.anthropic.domain.tools.Tool
import io.cequence.openaiscala.anthropic.service.{AnthropicService, AnthropicServiceFactory}
import io.cequence.openaiscala.domain.NonOpenAIModelId
import io.cequence.openaiscala.examples.ExampleBase

import scala.concurrent.Future

// requires `openai-scala-anthropic-client` as a dependency and `ANTHROPIC_API_KEY` environment variable to be set
object AnthropicCreateMessageWithCodeExecution extends ExampleBase[AnthropicService] {

  override protected val service: AnthropicService = AnthropicServiceFactory()

  private val model = NonOpenAIModelId.claude_sonnet_4_5_20250929

  private val messages: Seq[Message] = Seq(
    SystemMessage("You are a helpful assistant."),
    UserMessage(
      "Write a Python script that generates sales data and save it as sales_data.xlsx."
    )
  )

  override protected def run: Future[_] =
    for {
      response <- service.createMessage(
        messages,
        settings = AnthropicCreateMessageSettings(
          model = model,
          max_tokens = 4096,
          tools = Seq(Tool.codeExecution())
        )
      )

    } yield {
      val lastBashCodeExecutionFiles =
        response.bashCodeExecutionToolFileIds.lastOption.getOrElse(
          throw new RuntimeException(
            "No successful bash code execution result found in the response."
          )
        )

      // Display generated files that are accessible via File API
      if (lastBashCodeExecutionFiles.nonEmpty) {
        println()
        println("=" * 60)
        println("Generated Files (accessible via File API):")
        println("=" * 60)

        lastBashCodeExecutionFiles.foreach { fileId =>
          println(s"  File ID: ${fileId}")
          println(s"  Status: Generated by code execution")
          println(s"  Downloadable: Yes (use downloadFile endpoint)")
          println()
        }

        println("Note: These files can be downloaded using service.downloadFile(fileId)")
        println("Note: Use service.getFileMetadata(fileId) to get filename and MIME type")
        println("Note: Generated files are downloadable, unlike user-uploaded files")
        println("=" * 60)
        println()
      }

      response.blockContents.zipWithIndex.foreach { case (blockContent, index) =>
        println(s"Block ${index + 1}:")
        println(blockContent)
        println("=" * 60)
      }
    }
}
