package io.cequence.openaiscala.domain

object FineTune {

  // Fine-Tuning Job Integration
  sealed trait Integration

  // Integration with Weights and Biases
  // This specifies the project that metrics will be sent to.
  // Optionally, you can set an explicit display name for your run, add tags to your run,
  // and set a default entity (team, username, etc) to be associated with your run.
  case class WeightsAndBiases(
    // The name of the project that the new run will be created under.
    project: String,
    // A display name to set for the run. If not set, we will use the Job ID as the name.
    name: Option[String],
    // The entity to use for the run. This allows you to set the team or username of the WandB user that
    // you would like associated with the run. If not set, the default entity for the registered WandB API key is used.
    entity: Option[String],
    // A list of tags to be attached to the newly created run. These tags are passed through directly to WandB.
    // Some default tags are generated by OpenAI: "openai/finetune", "openai/{base-model}", "openai/{ftjob-abcdef}".
    tags: Seq[String]
  ) extends Integration

}
