package io.cequence.openaiscala.domain

case class MessageSpec(
  // The role of the messages author. One of system, user, assistant, or function.
  role: ChatRole,

  // The contents of the message. Content is required for all messages except assistant messages with function calls.
  content: Option[String],

  // The name of the author of this message. name is required if role is function, and
  // it should be the name of the function whose response is in the content.
  // May contain a-z, A-Z, 0-9, and underscores, with a maximum length of 64 characters.
  name: Option[String] = None,

  // The name and arguments of a function that should be called, as generated by the model.
  function_call: Option[FunctionCallSpec] = None
)

sealed trait ChatRole

object ChatRole {
  case object User extends ChatRole
  case object System extends ChatRole
  case object Assistant extends ChatRole

  case object Function extends ChatRole
}

case class FunctionCallSpec(
  name: String,
  arguments: String
)