package io.cequence.openaiscala.domain

sealed trait ToolCallSpec

case class FunctionCallSpec(
  // The name of the function to call
  name: String,

  // The arguments to call the function with, as generated by the model in JSON format.
  // Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema.
  // Validate the arguments in your code before calling your function.
  arguments: String
) extends ToolCallSpec
