package io.cequence.openaiscala.domain.responsesapi.tools

import io.cequence.openaiscala.domain.responsesapi.Input

/**
 * The output of a custom tool call from your code, being sent back to the model.
 *
 * @param callId
 *   The call ID, used to map this custom tool call output to a custom tool call.
 * @param output
 *   The output from the custom tool call generated by your code.
 * @param id
 *   The unique ID of the custom tool call output in the OpenAI platform (optional).
 */
final case class CustomToolCallOutput(
  callId: String,
  output: FunctionToolOutput,
  id: Option[String] = None
) extends Input {
  val `type`: String = "custom_tool_call_output"
}
