package io.cequence.openaiscala.domain.responsesapi.tools

import io.cequence.openaiscala.domain.responsesapi.Input

/**
 * A call to a custom tool created by the model.
 *
 * @param callId
 *   An identifier used to map this custom tool call to a tool call output.
 * @param input
 *   The input for the custom tool call generated by the model.
 * @param name
 *   The name of the custom tool being called.
 * @param id
 *   The unique ID of the custom tool call in the OpenAI platform (optional).
 */
final case class CustomToolCall(
  callId: String,
  input: String,
  name: String,
  id: Option[String] = None
) extends Input {
  val `type`: String = "custom_tool_call"
}