package io.cequence.openaiscala.domain.responsesapi.tools

import io.cequence.openaiscala.domain.responsesapi.{Input, ModelStatus}

/**
 * The output of a function tool call.
 *
 * @param callId
 *   The unique ID of the function tool call generated by the model
 * @param output
 *   A JSON string of the output of the function tool call
 * @param id
 *   The unique ID of the function tool call output
 * @param status
 *   The status of the item
 */
final case class FunctionToolCallOutput(
  callId: String,
  output: String,
  id: Option[String] = None,
  status: Option[ModelStatus] = None // in_progress, completed, or incomplete
) extends Input {
  val `type`: String = "function_call_output"
}
