package io.cequence.openaiscala.domain.responsesapi.tools

import io.cequence.openaiscala.domain.responsesapi.Input

/**
 * The output of a local shell tool call.
 *
 * @param id
 *   The unique ID of the local shell tool call generated by the model.
 * @param output
 *   A JSON string of the output of the local shell tool call.
 * @param status
 *   The status of the item. One of in_progress, completed, or incomplete. TODO: introduce enum
 */
final case class LocalShellToolCallOutput(
  id: String,
  output: String,
  status: Option[String] = None
) extends Input {
  val `type`: String = "local_shell_call_output"
}
